name: Convert Markdown to PDF

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-xetex fonts-roboto

      - name: Convert Markdown to PDF
        run: |
          pandoc README.md -o Martin_Miller_resume.pdf --pdf-engine=xelatex -V mainfont="Roboto" -V geometry:margin=1in

      - name: Commit PDF to repository
        run: |
          mkdir -p PDF
          mv Martin_Miller_resume.pdf PDF/
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add PDF/Martin_Miller_resume.pdf
          git commit -m "Add generated PDF from README" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
