name: Convert Markdown to Coherent JSON

on:
  push:
    branches:
      - main
    paths:
      - README.md
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc jq

      - name: Convert Markdown to JSON
        run: |
          mkdir -p json_output
          pandoc README.md -t json -o json_output/output.json

      - name: Process JSON to coherent blocks
        run: |
          jq -r '[.blocks[] | select(.t == "Para") | .c | join(" ") | {text: .}]' json_output/output.json > json_output/coherent_output.json

      - name: Commit JSON to repository
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add json_output/coherent_output.json
          git commit -m "Add coherent JSON output from README" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
