name: Convert Markdown to Plain Text and JSON

on:
  push:
    branches:
      - main
    paths:
      - README.md
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc jq

      - name: Convert Markdown to Plain Text
        run: |
          mkdir -p output
          pandoc README.md -t plain -o output/output.txt

      - name: Convert Plain Text to JSON
        run: |
          # Read the plain text, split into coherent blocks, and format as JSON
          awk 'BEGIN {print "["} {print "{\"text\": \"" $0 "\"},"} END {print "]"}' output/output.txt | sed '$ s/,$//' > output/output.json

      - name: Commit JSON to repository
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add output/output.json
          git commit -m "Add JSON output from README" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
